name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/lovelace-tam-card/lovelace-tam-card
          npm install
          npm run build

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/lovelace-tam-card/lovelace-tam-card/dist/tam-card.js
          asset_name: tam-card.js
          tag: ${{ github.ref }}
          overwrite: true
